runtime: python
env: flex

runtime_config:
  python_version: 3

entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

env_variables:
  prod: "true"
